### ISSUE TITLE
Images not displaying properly

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#1]
Images not displaying properly on many sites.  Problem is most likely related to file path problems.

Our instance of WordPress have multiple forms of file paths depending on when the site was created (i.e. what version of WordPress was running when they were created, see:
https://codex.wordpress.org/Multisite_Network_Administration#Uploaded_File_Path

**Comment by atrus1701** [comment]
[on pages] fixed.
