### ISSUE TITLE
Org Hub users not displaying properly

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#10]
Org Hub users not displaying properly after import.  See:
https://devpages.uncc.edu/wp-admin/network/admin.php?page=orghub-users&tab=list

Last process date message is:

> The last process users was preformed on 2015-08-21 19:54:39.
> Successfully done processing the user list.

**Comment by marpa** [comment]
Org Hub sites processing works, see:
https://devpages.uncc.edu/wp-admin/network/admin.php?page=orghub-sites

Last process date message is not correct.  Message is:

> The sites lists has never been cached.

**Comment by marpa** [comment]
For Org Hub user data, see:
[Org Hub Users AWS Import](https://docs.google.com/spreadsheets/d/1zH0ilGupHhiepyTOWz70-JMVh589nWhgvfyeYKH6nv4/edit#gid=0)

This spreadsheet has sheets for prod and dev

**Comment by marpa** [comment]
I just noticed that the Org Hub user export does NOT export Status information (i.e. active or inactive).  see: https://github.com/clas-web/organization-hub/issues/73

**Comment by atrus1701** [comment]
Need to test exporting with the status column.

**Comment by atrus1701** [comment]
fixed.
