### ISSUE TITLE
Appointments + settings incorrect

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#11]
The Appointments + plugin used on the Project Mosaic site is not working properly.  Specifically, the Service Providers list is not populated, compare:
https://devprojectmosaic.uncc.edu/wp-admin/admin.php?page=app_settings&tab=workers
https://projectmosaic.uncc.edu/wp-admin/admin.php?page=app_settings&tab=workers

It might be possible to simply re-specify service provider...

(originally, the dev instance of this settings page specified aadams73 (i.e. the 1st user in the list) as the service provider for all services listed.  I attempted to reset one of these to one of the service providers specified in prod instance, but when I saved, ID numbers all changed....)

**Comment by marpa** [comment]
Service providers list is now populated correctly.  However, other data about service providers is still different, compare:
https://devprojectmosaic.uncc.edu/wp-admin/admin.php?page=app_settings&tab=workers
https://projectmosaic.uncc.edu/wp-admin/admin.php?page=app_settings&tab=workers

If you click on "More Info" for a given service provider, prod will show padding times and location, whereas dev does not.

As well, the working hours for each servicer provider is no longer defined in dev, compare:
https://devprojectmosaic.uncc.edu/wp-admin/admin.php?page=app_settings&tab=working_hours&app_provider_id=889
https://projectmosaic.uncc.edu/wp-admin/admin.php?page=app_settings&tab=working_hours&app_provider_id=1373

As a result of no defined hours and no specification of the dummy service provider (i.e. default if none selected), initial appt page is different, compare:
The initial appt page is different on prod and dev, compare:
https://devprojectmosaic.uncc.edu/appointment/
https://projectmosaic.uncc.edu/appointment/

It is possible to re-specify the default service provider and re-select the working hours and everything should work ok....  These issues most likely due to new user ids...

**Comment by atrus1701** [comment]
fixed.
