### ISSUE TITLE
Events plugin issues

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#12]
The Project Mosaic site uses an Events plugin that is not working the same in dev, compare:
https://devprojectmosaic.uncc.edu/events-list/
https://projectmosaic.uncc.edu/events-list/

The issue may be related to the event custom post type, compare:
https://devprojectmosaic.uncc.edu/wp-admin/edit.php?post_type=event
https://projectmosaic.uncc.edu/wp-admin/edit.php?post_type=event

The dev events listing page shows no events found, even though it has the same number of events in the All, Published, Drafts and Trash counts....

There are also differences in the Events Booking Dashboard, see:
https://devprojectmosaic.uncc.edu/wp-admin/edit.php?post_type=event&page=events-manager-bookings
https://projectmosaic.uncc.edu/wp-admin/edit.php?post_type=event&page=events-manager-bookings

Event categories, Event Tags and Locations, Forms Editor seem to be okay in dev...  As well, the full calendar looks ok, compare:
https://devprojectmosaic.uncc.edu/events/
https://projectmosaic.uncc.edu/events/

**Comment by atrus1701** [comment]
fixed.
