### ISSUE TITLE
Images on feedwordpress sites have wrong urls

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#13]
Images on feedwordpress sites such as Thinking Matters that were imported prior to the migration to AWS have wrong image path, see:
https://thinkingmatters.uncc.edu/blog/author/miwest/

Image with wrong paths use following syntax:
https://clas-pages.uncc.edu/mark-west/files/2016/02/To-Kill-a-Mockingbird-209x300.jpeg

Correct image paths should be:
https://clas-pages.uncc.edu/mark-west/wp-content/uploads/sites/322/2016/03/Myles_Hassel-IM-300x241.png

**Comment by atrus1701** [comment]
fixed.
