### ISSUE TITLE
Post attribution is incorrect on some sites

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#14]
Some sites, such as Thinking Matters, have incorrect post attribution, see:
https://thinkingmatters.uncc.edu/blog/author/smichael/
https://thinkingmatters.uncc.edu/blog/author/greg-weeks/

Some of this incorrect attribution affects (such as the one above) only posts imported after March 8th (i.e. after migration to AWS).  Other misattribution affects posts before and after migration, see:
https://thinkingmatters.uncc.edu/blog/author/sshodge/

Posts attributed to Susan Hodge should were authored by James Tabor, see:
https://thinkingmatters.uncc.edu/blog/author/james-tabor/

**Comment by atrus1701** [comment]
fixed.  Just compared the MCNC settings and updated any synced posts that had the wrong author.
