### ISSUE TITLE
Jetpack widget visibility not working

### ISSUE THREAD

**Issue by clas-web** [atrus1701/mcnc_to_aws_conversion#15]
Jetpack widget visibility not working.  On sites that have this module activated, there is no visibility option in the customizer (usually appears at the bottom of a given widget's settings.

The visibility option is available from the Appearance > Widgets page, see:
https://projectmosaic.uncc.edu/wp-admin/widgets.php

**Comment by marpa** [comment]
Cannot reproduce in current environment
