### ISSUE TITLE
AWS instances of WordPress running slow

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#16]
AWS instances of pages.uncc.edu was running slow.  Tuning Apache seemed to have helped, see:
http://imperialwicket.com/tuning-apache-for-a-low-memory-server-like-aws-micro-ec2-instances/

sites.uncc.edu also has times when it runs slow.  Perhaps same tuning should be applied

**Comment by atrus1701** [comment]
Updated the apache settings to be optimized for the instance's memory amount.  I believe this has fixed the issue.

**Comment by atrus1701** [comment]
Will be fixed when we upgrade the server this week...

**Comment by atrus1701** [comment]
Upgraded the server.
