### ISSUE TITLE
Exchange Online events categories missing

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#17]
Exchange Online events categories missing, compare:
- https://exchange.uncc.edu/wp-admin/edit-tags.php?taxonomy=category&post_type=event
- https://clas-incubator-wp.uncc.edu/exchange/wp-admin/edit-tags.php?taxonomy=event-category&post_type=event

AWS version of site lists as event categories the same categories as posts...

**Comment by atrus1701** [comment]
Fixed by updating the News Hub theme.
