### ISSUE TITLE
Dev wordpress instances very slow

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#19]
Both devpages.uncc.edu and devsites.uncc.edu are very slow to load, see:
https://devpages.uncc.edu
https://devsites.uncc.edu

**Comment by atrus1701** [comment]
I updated both devpages and devsites Apache settings this morning so this should make the server faster.

**Comment by marpa** [comment]
devsites is considerably slower than devpages, compare:
https://devsites.uncc.edu/
https://devpages.uncc.edu/

**Comment by marpa** [comment]
Was able to access devexchange site recently, but now, get the following error:

> This site can’t be reached
> devexchange.uncc.edu took too long to respond.
> ERR_TIMED_OUT

and now its back... performance is erratic, slow for awhile and then okay....

**Comment by atrus1701** [comment]
This is will be fixed with a upgrade of the server.
