### ISSUE TITLE
Devsite media files not displaying

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#20]
Media on devsites not displaying, compare:
- https://devexchange.uncc.edu/wp-content/uploads/sites/14/2016/01/mt_Zion_Dig_2015_1_Rachel_Ward-324x216.jpg
- https://exchange.uncc.edu/wp-content/uploads/sites/14/2016/01/mt_Zion_Dig_2015_1_Rachel_Ward-324x216.jpg

The wp-content/uploads directory is empty on devsites...

**Comment by marpa** [comment]
When media files are uploaded via FTP, permissions are not set correctly, compare:
- https://exchange.uncc.edu/wp-content/uploads/sites/14/2007/12/cj_mock_trial_4_b.jpg
- https://devexchange.uncc.edu/wp-content/uploads/sites/14/2007/12/cj_mock_trial_4_b.jpg

error is:

> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator, clas-web@uncc.edu and inform them of the time the error occurred, and anything you might have done that may have caused the error.
> 
> More information about this error may be available in the server error log.

When uploaded via FTP:
- permissions are set to 644
- owner = ec2-user
- group = apache

In contrast in PROD:
- permissions are set to 775
- owner = apache
- group = apache

**Comment by marpa** [comment]
I added media files for the dev version of the Exchange online site and then chown to apache and chmod 775 recursively, but images still do not appear, see:
https://devexchange.uncc.edu/wp-content/uploads/sites/14/2016/01/mt_Zion_Dig_2015_1_Rachel_Ward-300x200.jpg

As well, uploaded php code does not execute as expected...see:
/var/www/wordpress/test1/html/wp-content/themes/unc-charlotte-news-hub-theme/variations/uncc/templates/part/header.php

This file updates the uncc logo to include a link to www.uncc.edu, but site is not updated, see:
https://devexchange.uncc.edu/

**Comment by marpa** [comment]
Comparing PROD file permissions with permissions on DEV for files uploaded via FTP
PROD: rwxrwsr-x
DEV: rwxrwxr-x

I ran chmod again, this time as chmod 2775 recursively, but did not allow images to display nor php file updates to execute...

**Comment by marpa** [comment]
Currently I'm able to connect to the devsites server via SFTP and can browse files and folders, but I cannot view, edit or upload.  When I do, I get the following error:

> Could not change directory to “/var/www/wordpress/test1/html/<<filepath>>”. 
> Make sure you have permission to modify this file.

**Comment by atrus1701** [comment]
The permissions are not being set correctly when running the create.php script.  This will be fixed by running a chown and chmod command in the script after the folder is created.

**Comment by marpa** [comment]
I am not able to open existing files or upload updates... I tried to chown and chmod files and folders via ssh, but I get permission denied, see:

> drwxrwsr-x 8 apache apache 4096 Apr  6 13:08 .
> drwxrwsr-x 9 apache apache 4096 Apr  5 12:00 ..
> d-wx--Sr-t 3 root   apache 4096 Apr  6 10:58 test1
> d-wx--Sr-t 3 root   apache 4096 Apr  6 11:05 test2
> d-wx--Sr-t 3 root   apache 4096 Apr  6 11:40 test3
> d-wx--Sr-t 3 root   apache 4096 Apr  6 12:09 test4
> d-wx--Sr-t 3 root   apache 4096 Apr  6 12:38 test5
> d-wx--Sr-t 3 root   apache 4096 Apr  6 13:08 test6
> [ec2-user@devsites wordpress]$ cd test1
> -bash: cd: test1: Permission denied

**Comment by atrus1701** [comment]
fixed
