### ISSUE TITLE
Some sites not rendering properly

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#3]
Some sites not rendering properly.  These are sites that use older themes

**Comment by marpa** [comment]
Many sites that are having display issues are sites that use themes that were installed only on clas-pages, not pages.  Have added:
- twentyeleven-uncc
- 2010-translucence
  -uncc-child

Other themes will likely need to be added from clas-pages.

**Comment by atrus1701** [comment]
fixed.
