### ISSUE TITLE
Users assigned to sites are incorrect

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#5]
Users assigned to sites are incorrect.  Users assigned to a site are those from the new site with the same blog id as the old site.

Users assigned to a site should be those from the old site whose blog id corresponds to the new version of that site.

For example, see:
https://clas-pages.uncc.edu/wp-admin/network/site-users.php?id=245
https://devpages.uncc.edu/wp-admin/network/site-users.php?id=245

Should be:
https://clas-pages.uncc.edu/wp-admin/network/site-users.php?id=245
https://devpages.uncc.edu/wp-admin/network/site-users.php?id=221

**Comment by atrus1701** [comment]
04abceb18e81e4b6f1ecfa9f2569ae2df0e904e4
