### ISSUE TITLE
Some images are missing on some sites

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#7]
Some images are missing on some sites.
Sidebar image missing:
https://clas-pages.uncc.edu/john-david-smith/
https://devclaspages.uncc.edu/john-david-smith/

Header image missing:
https://clas-pages.uncc.edu/oat/
https://devclaspages.uncc.edu/oat/

Page image missing:
https://clas-pages.uncc.edu/kirill-afonin/
https://devclaspages.uncc.edu/kirill-afonin/

Custom header and background image missing:
https://clas-pages.uncc.edu/justin-conrad/
https://devclaspages.uncc.edu/justin-conrad/

Header height is different:
https://clas-pages.uncc.edu/john-david-smith/
https://devclaspages.uncc.edu/john-david-smith/

**Comment by marpa** [comment]
Have confirmed that the missing images are in the correct directory on the dev instance, see:
https://clas-pages.uncc.edu/mark-west/blog/2016/02/21/monday-missive-february-22-2016/
https://clas-pages.uncc.edu/mark-west/files/2016/02/To-Kill-a-Mockingbird-209x300.jpeg

https://devclaspages.uncc.edu/mark-west/blog/2016/02/21/monday-missive-february-22-2016/
https://devclaspages.uncc.edu/mark-west/files/2016/02/To-Kill-a-Mockingbird.jpeg

It is odd that the dev instance points to a slightly different version of the image:
To-Kill-a-Mockingbird.jpeg
To-Kill-a-Mockingbird-209x300.jpeg

clas-pages.uncc.edu has the following image path:
wp-content/blogs.dir/352/files/2016/02

devclaspages.uncc.edu has the following path:
wp-content/uploads/sites/322/2016/02

**Comment by marpa** [comment]
Missing images seem to occur only on devclaspages.uncc.edu sites, see:
https://devclaspages.uncc.edu/dennis-ogburn/
https://devclaspages.uncc.edu/james-tabor/

Images are NOT missing on multi-domain or domain-mapped sites, see:
https://devclaschemistry.uncc.edu/markus-etzkorn/
https://devclasmath.uncc.edu/jeong-lim-chae/
https://devfilmfest.uncc.edu/
(filmfest site is missing header image, but not post images)

**Comment by marpa** [comment]
Missing images on devclaspages.uncc.edu sites seem to only occur on sites which:
- use UNC Charlotte Faculty and Staff theme
- have had images added recently

Case in point, the following site has no missing images, see:
https://devclaspages.uncc.edu/katherine-stephenson/

Last time an image was uploaded was in 2012.  Could this be using different file paths originally then images uploaded more recently?

**Comment by marpa** [comment]
Missing image problems seem to be file url issues.  The file url in the media library is correct, but wrong in posts, see:
https://devclaspages.uncc.edu/mark-west/files/2016/02/To-Kill-a-Mockingbird.jpeg
https://devclaspages.uncc.edu/mark-west/wp-content/uploads/sites/322/2016/02/To-Kill-a-Mockingbird.jpeg

**Comment by atrus1701** [comment]
4463b36bbd3f3ddbd66fb9481e4d469f916524e7
