### ISSUE TITLE
User roles issues

### ISSUE THREAD

**Issue by marpa** [atrus1701/mcnc_to_aws_conversion#9]
On most, maybe all, sites registered users of a given site have the role of "none."   See:
https://devsites.uncc.edu/wp-admin/users.php
https://devclaspages.uncc.edu/oat/wp-admin/users.php
https://devpages.uncc.edu/wp-admin/users.php

When adding a new user to a site or changing the roles of selected users, no roles are available to choose from, see:
https://devsites.uncc.edu/wp-admin/users.php
https://devsites.uncc.edu/wp-admin/users.php?page=wpmu_ldap_adduser.functions.php

**Comment by atrus1701** [comment]
04abceb18e81e4b6f1ecfa9f2569ae2df0e904e4
